### ISSUE TITLE
Folder functionality causes CTD on dedicated server

### ISSUE THREAD

**Issue by AaronAyante** [StarCpt/SE-GpsFolders#3]
The only seemingly relevant part of the error log:

2024-04-01 12:18:34.946 - Thread:   1 ->  MyGuiScreenMission MyGuiScreenBase.UnloadContent - START
2024-04-01 12:18:34.946 - Thread:   1 ->  MyGuiScreenMission MyGuiScreenBase.UnloadContent - END
2024-04-01 12:18:38.164 - Thread:   1 ->  MyGuiScreenTerminal MyGuiScreenBase.LoadContent
2024-04-01 12:18:44.781 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at GpsFolders.Extensions.SetFolderTag(Row row, String tag)
   at Sandbox.Graphics.GUI.MyGuiControlTextbox.OnTextChanged()
   at Sandbox.Graphics.GUI.MyGuiControlTextbox.HandleTextInputBuffered(MyGuiControlBase& ret)
   at Sandbox.Graphics.GUI.MyGuiControlTextbox.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-04-01 12:18:44.782 - Thread:   1 ->  Showing message
2024-04-01 12:18:45.291 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_203_630
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 168
PCUCount: 11669
IsHang: False
GCMemory: 2107
GCMemoryAllocated: 2107
HWAvailableMemory: 11236
ProcessPrivateMemory: 15240
AnalyticId: SE
================================== OFNI HSARC ==================================

**Comment by StarCpt** [comment]
The stacktrace doesn't really tell me anything in this case, what were you doing at the time of the crash? (created a folder, clicked on an entry, etc) I don't *think* it's a dedicated server problem since there haven't been any other reports of it. There is a bug where if you change a folder's name to another existing folder it crashes the game but that doesn't seem to be issue here.

**Comment by AaronAyante** [comment]
I was attempting to create a folder. I will retry again tomorrow with ProcDump running against the SE.exe and see what it generates.

**Comment by Maweypeyyu** [comment]
**Workaround is at the bottom!**

---

I have the same issue using this plugin with PluginLoader and the latest SE version. (Note that this plugin is pinned to commit id f3a4614db4b63aa518e313ba691583a7ca219a03 [in PluginHub](https://github.com/sepluginloader/PluginHub/blob/main/Plugins/GpsFolders.xml#L19C11-L19C51) and not to the latest version.)

After checking out this repo and loading it via the dev mode in PluginLoader and experimenting around I found the following to be the culprit:

Some mods (SEWorldGen is the one in my case) may create GPS markers that do not have a description (i.e., `null` not `""`). Every other method for creating GPS in SpaceEngineers (in-game, I mean) ensures that there is a description so this usually never triggers a crash.

The crash indeed happens in [this line](https://github.com/StarCpt/SE-GpsFolders/blob/master/SE-GpsFolders/Extensions.cs#L121).

Here's a tested (and working) fix to be used for the if-block in L119:
```csharp
                if (IsFolderIdValid(id))
                {
                    StringBuilder newGpsDescriptionBuilder = new StringBuilder(startTag, 255);
                    newGpsDescriptionBuilder.Append(id);
                    newGpsDescriptionBuilder.Append(endTag);

                    if (gps.Description != null)
                    {
                        if (!gps.Description.StartsWith("\n"))
                        {
                            newGpsDescriptionBuilder.Append("\n");
                        }

                        newGpsDescriptionBuilder.Append(gps.Description);
                    }

                    gps.Description = newGpsDescriptionBuilder.ToString();
                }
```

Could you include this fix if you agree with it (and also make sure that the new commit id gets published to PluginHub)?

---

**For anyone else as a workaround right now:**
Before typing anything in the `Folder Name:` input field, first type something into the GPS description field. After it, typing a folder name should work.

**Comment by AaronAyante** [comment]
> **Workaround is at the bottom!**
> 
> I have the same issue using this plugin with PluginLoader and the latest SE version. (Note that this plugin is pinned to commit id [f3a4614](https://github.com/StarCpt/SE-GpsFolders/commit/f3a4614db4b63aa518e313ba691583a7ca219a03) [in PluginHub](https://github.com/sepluginloader/PluginHub/blob/main/Plugins/GpsFolders.xml#L19C11-L19C51) and not to the latest version.)
> 
> After checking out this repo and loading it via the dev mode in PluginLoader and experimenting around I found the following to be the culprit:
> 
> Some mods (SEWorldGen is the one in my case) may create GPS markers that do not have a description (i.e., `null` not `""`). Every other method for creating GPS in SpaceEngineers (in-game, I mean) ensures that there is a description so this usually never triggers a crash.
> 
> The crash indeed happens in [this line](https://github.com/StarCpt/SE-GpsFolders/blob/master/SE-GpsFolders/Extensions.cs#L121).
> 
> Here's a tested (and working) fix to be used for the if-block in L119:
> 
> ```cs
>                 if (IsFolderIdValid(id))
>                 {
>                     StringBuilder newGpsDescriptionBuilder = new StringBuilder(startTag, 255);
>                     newGpsDescriptionBuilder.Append(id);
>                     newGpsDescriptionBuilder.Append(endTag);
> 
>                     if (gps.Description != null)
>                     {
>                         if (!gps.Description.StartsWith("\n"))
>                         {
>                             newGpsDescriptionBuilder.Append("\n");
>                         }
> 
>                         newGpsDescriptionBuilder.Append(gps.Description);
>                     }
> 
>                     gps.Description = newGpsDescriptionBuilder.ToString();
>                 }
> ```
> 
> Could you include this fix if you agree with it (and also make sure that the new commit id gets published to PluginHub)?
> 
> **For anyone else as a workaround right now:** Before typing anything in the `Folder Name:` input field, first type something into the GPS description field. After it, typing a folder name should work.

What's odd is the crash happens when I try to type in the Folder name field - soon as I hit a single letter, bam, CTD.

**Comment by Maweypeyyu** [comment]
Which is happening because the plugin/mod updates the description field each time a letter is typed into the `Folder Name` field.

**Comment by AaronAyante** [comment]
> Which is happening because the plugin/mod updates the description field each time a letter is typed into the `Folder Name` field.

Ah, my bad - I misunderstood your initial reply to mean I had to fill something in hah. Sorry about that!

**Comment by StarCpt** [comment]
> **Workaround is at the bottom!**
> 
> I have the same issue using this plugin with PluginLoader and the latest SE version. (Note that this plugin is pinned to commit id [f3a4614](https://github.com/StarCpt/SE-GpsFolders/commit/f3a4614db4b63aa518e313ba691583a7ca219a03) [in PluginHub](https://github.com/sepluginloader/PluginHub/blob/main/Plugins/GpsFolders.xml#L19C11-L19C51) and not to the latest version.)
> 
> After checking out this repo and loading it via the dev mode in PluginLoader and experimenting around I found the following to be the culprit:
> 
> Some mods (SEWorldGen is the one in my case) may create GPS markers that do not have a description (i.e., `null` not `""`). Every other method for creating GPS in SpaceEngineers (in-game, I mean) ensures that there is a description so this usually never triggers a crash.
> 
> The crash indeed happens in [this line](https://github.com/StarCpt/SE-GpsFolders/blob/master/SE-GpsFolders/Extensions.cs#L121).
> 
> Here's a tested (and working) fix to be used for the if-block in L119:
> 
> ```cs
>                 if (IsFolderIdValid(id))
>                 {
>                     StringBuilder newGpsDescriptionBuilder = new StringBuilder(startTag, 255);
>                     newGpsDescriptionBuilder.Append(id);
>                     newGpsDescriptionBuilder.Append(endTag);
> 
>                     if (gps.Description != null)
>                     {
>                         if (!gps.Description.StartsWith("\n"))
>                         {
>                             newGpsDescriptionBuilder.Append("\n");
>                         }
> 
>                         newGpsDescriptionBuilder.Append(gps.Description);
>                     }
> 
>                     gps.Description = newGpsDescriptionBuilder.ToString();
>                 }
> ```
> 
> Could you include this fix if you agree with it (and also make sure that the new commit id gets published to PluginHub)?
> 
> **For anyone else as a workaround right now:** Before typing anything in the `Folder Name:` input field, first type something into the GPS description field. After it, typing a folder name should work.

Sorry for the late reply, I'll add a fix for the null description

**Comment by StarCpt** [comment]
I added a fix for this in the latest update.

https://github.com/StarCpt/SE-GpsFolders/commit/96fe05aca434362bf2b78c3f32ef212f48d54670

**Comment by Maweypeyyu** [comment]
Thanks, also for updating the plugin hub immediately!
