### ISSUE TITLE
Crash while searching gps record

### ISSUE THREAD

**Issue by Thermi** [StarCpt/SE-GpsFolders#6]
```
2024-07-02 23:04:52.408 - Thread:   1 ->  MyGuiScreenTerminal MyGuiScreenBase.LoadContent
2024-07-02 23:04:55.240 - Thread:   1 ->  Exception: System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at GpsFolders.Extensions.SetFolderId(MyGps gps, String id)
   at GpsFolders.Extensions.SetFolderId(Row row, String id)
   at Sandbox.Graphics.GUI.MyGuiControlTextbox.OnTextChanged()
   at GpsFolders.MyTerminalGpsControllerPatches.Patch_OnTableItemSelected.Postfix(MyGuiControlTable sender, MyGuiControlTextbox ___m_panelInsName, MyGuiControlMultilineEditableText ___m_panelInsDesc, MyGuiControlTextbox ___m_xCoord, MyGuiControlTextbox ___m_yCoord, MyGuiControlTextbox ___m_zCoord, MyGuiControlSlider ___m_sliderHue, MyGuiControlSlider ___m_sliderSaturation, MyGuiControlSlider ___m_sliderValue, MyGuiControlTextbox ___m_textBoxHex, MyGuiControlCheckbox ___m_checkInsShowOnHud, MyGuiControlCheckbox ___m_checkInsAlwaysVisible, MyGuiControlButton ___m_buttonCopy, MyGuiControlSearchBox ___m_searchBox)
   at Sandbox.Game.Gui.MyTerminalGpsController.OnTableItemSelected_Patch1(MyTerminalGpsController this, MyGuiControlTable sender, EventArgs args)
   at System.DelegateExtensions.InvokeIfNotNull[T1,T2](Action`2 handler, T1 arg1, T2 arg2)
   at Sandbox.Graphics.GUI.MyGuiControlTable.OnFocusChanged(Boolean focus)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.set_FocusedControl(MyGuiControlBase value)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-02 23:04:55.246 - Thread:   1 ->  Exception occurred: System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at GpsFolders.Extensions.SetFolderId(MyGps gps, String id)
   at GpsFolders.Extensions.SetFolderId(Row row, String id)
   at Sandbox.Graphics.GUI.MyGuiControlTextbox.OnTextChanged()
   at GpsFolders.MyTerminalGpsControllerPatches.Patch_OnTableItemSelected.Postfix(MyGuiControlTable sender, MyGuiControlTextbox ___m_panelInsName, MyGuiControlMultilineEditableText ___m_panelInsDesc, MyGuiControlTextbox ___m_xCoord, MyGuiControlTextbox ___m_yCoord, MyGuiControlTextbox ___m_zCoord, MyGuiControlSlider ___m_sliderHue, MyGuiControlSlider ___m_sliderSaturation, MyGuiControlSlider ___m_sliderValue, MyGuiControlTextbox ___m_textBoxHex, MyGuiControlCheckbox ___m_checkInsShowOnHud, MyGuiControlCheckbox ___m_checkInsAlwaysVisible, MyGuiControlButton ___m_buttonCopy, MyGuiControlSearchBox ___m_searchBox)
   at Sandbox.Game.Gui.MyTerminalGpsController.OnTableItemSelected_Patch1(MyTerminalGpsController this, MyGuiControlTable sender, EventArgs args)
   at System.DelegateExtensions.InvokeIfNotNull[T1,T2](Action`2 handler, T1 arg1, T2 arg2)
   at Sandbox.Graphics.GUI.MyGuiControlTable.OnFocusChanged(Boolean focus)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.set_FocusedControl(MyGuiControlBase value)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-02 23:04:55.246 - Thread:   1 ->  Showing message
2024-07-02 23:04:55.246 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-02 23:04:55.246 - Thread:   1 ->  var exception = System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at GpsFolders.Extensions.SetFolderId(MyGps gps, String id)
   at GpsFolders.Extensions.SetFolderId(Row row, String id)
   at Sandbox.Graphics.GUI.MyGuiControlTextbox.OnTextChanged()
   at GpsFolders.MyTerminalGpsControllerPatches.Patch_OnTableItemSelected.Postfix(MyGuiControlTable sender, MyGuiControlTextbox ___m_panelInsName, MyGuiControlMultilineEditableText ___m_panelInsDesc, MyGuiControlTextbox ___m_xCoord, MyGuiControlTextbox ___m_yCoord, MyGuiControlTextbox ___m_zCoord, MyGuiControlSlider ___m_sliderHue, MyGuiControlSlider ___m_sliderSaturation, MyGuiControlSlider ___m_sliderValue, MyGuiControlTextbox ___m_textBoxHex, MyGuiControlCheckbox ___m_checkInsShowOnHud, MyGuiControlCheckbox ___m_checkInsAlwaysVisible, MyGuiControlButton ___m_buttonCopy, MyGuiControlSearchBox ___m_searchBox)
   at Sandbox.Game.Gui.MyTerminalGpsController.OnTableItemSelected_Patch1(MyTerminalGpsController this, MyGuiControlTable sender, EventArgs args)
   at System.DelegateExtensions.InvokeIfNotNull[T1,T2](Action`2 handler, T1 arg1, T2 arg2)
   at Sandbox.Graphics.GUI.MyGuiControlTable.OnFocusChanged(Boolean focus)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.set_FocusedControl(MyGuiControlBase value)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
2024-07-02 23:05:02.047 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_204_018
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 3732
PCUCount: 119833
IsHang: False
GCMemory: 2437
GCMemoryAllocated: 2437
HWAvailableMemory: 16464
ProcessPrivateMemory: 10130
AnalyticId: SE
================================== OFNI HSARC ==================================

2024-07-02 23:05:02.047 - Thread:   1 ->  Log Closed
```

**Comment by StarCpt** [comment]
Thanks for the report, this has been fixed in v1.6.6.
